kind: Deployment
apiVersion: apps/v1
metadata:
  name: filemgmt
  namespace: camunda-workers
  labels:
    app: digit-plattform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filemgmt
  template:
    metadata:
      labels:
        app: filemgmt
        app.kubernetes.io/name: filemgmt
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
        - name: filemgmt
          image: ghcr.io/haninge-digit/digit-service-filemgmt:latest
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
          env:
            - name: DEBUG
              value: 'false'
            - name: TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: ms365filemgmt-secret
                  key: AD_TENANT_ID
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ms365filemgmt-secret
                  key: AD_CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ms365filemgmt-secret
                  key: AD_CLIENT_SECRET
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          # livenessProbe:
          #   httpGet:
          #     path: /probe/liveness
          #     port: http
          #     scheme: HTTP
          #   timeoutSeconds: 1
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext: {}
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: filemgmt
  namespace: camunda-workers
  labels:
    app: digit-plattform
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  selector:
    app: filemgmt
  type: ClusterIP
